services:
  flowapi:
    image: thesmallhancat/flow2api:latest
    container_name: flowapi
    volumes:
      - ./data:/app/data
      - ./config/setting_warp.toml:/app/config/setting.toml
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - warp-network
      - gateway-network

networks:
  warp-network:
    external: true
  gateway-network:
    external: true